### ISSUE TITLE
Clarification about callbacks

### ISSUE THREAD

**Issue by cristianvogel** [dhowe/GML#2]
Hi Dhowe, I am a bit puzzled about how TestGrammerGML.pde is resolving the callbacks. Where are the functions which do the work on the call back from the grammar, such as `uniquePair() or `conjugate()? 

I remember writing them in 2011 and was hoping to re-write them if necessary, but I'm puzzled about where the original routines can be found?

**Comment by dhowe** [comment]
Here: https://github.com/dhowe/GML/blob/master/src/GrammarGML.java#L94
and here: https://github.com/dhowe/GML/blob/master/src/GrammarGML.java#L75
