### ISSUE TITLE
Problems with migration of Processing code into IntelliJ

### ISSUE THREAD

**Issue by cristianvogel** [dhowe/GML#4]
Hi Daniel, 

Ok, this might be a bit of an overly complicated thing... but since my original GML from 2011 was a Processing sketch, and you already moved into Java proper, then I decided to try to continue the development in a modern IDE, IntelliJ... 

Its kind of working, I have imported all of Processing and RiTa and everything to try and a working starting point...  the original Sketch version of the code is running without exceptions (there were lots and lots at first) -- but it seems the callbacks are being weird. They do arrive to the methods, but there seems to be a problem with the  < > that surround the Tokens in the Grammar files. So the word to be Conjugated for example from `conjugate(singular, 3rd, ing, `< nonMovementVerb >`);`  is being processed with the < > so it just doesn't work... 

Have you come across this before? Any clues? Here is the whole archive project which you can open in IntelliJ if you have time to take a look....

[GenMov2019.zip](https://github.com/dhowe/GML/files/2994546/GenMov2019.zip)

**Comment by cristianvogel** [comment]
<img width="1887" alt="Screenshot 2019-03-22 01 50 11" src="https://user-images.githubusercontent.com/12829050/54794691-0fa05480-4c49-11e9-9b8b-6b5d2b8b0641.png">

**Comment by dhowe** [comment]
So can you isolate this in a minimal test? The shortest java file, with a main, that demonstrates the problem? This will help me to debug (I don't use IntelliJ)...

But if the problem _only_ happens in IntelliJ, then it likely has to do with file associations or encoding. If you are using an external grammar file, make sure that it is set to be a plain-text file with UTF-8 encoding.
